import 'package:firebase_core/firebase_core.dart';

/// Replace this file with the one generated by `flutterfire configure`.
///
/// The placeholder keeps the project compilable while the group finishes the
/// Firebase Console setup for its own project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'Firebase ainda nao foi configurado. Rode `flutterfire configure` '
      'e substitua este arquivo pelo gerado pela CLI.',
    );
  }
}
