// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJVilQkLS2g5T-f__6yW6BikoZT0Lp9Y',
    appId: '1:122927839963:web:183a8c40573e4c8fe1aafe',
    messagingSenderId: '122927839963',
    projectId: 'culturelocal-b8f51',
    authDomain: 'culturelocal-b8f51.firebaseapp.com',
    storageBucket: 'culturelocal-b8f51.firebasestorage.app',
    measurementId: 'G-M2DJJ93KXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBckdGEkQc-BpYmjGb8EajdO_ZH7ryA2Do',
    appId: '1:122927839963:android:9a628f85d88ff3dde1aafe',
    messagingSenderId: '122927839963',
    projectId: 'culturelocal-b8f51',
    storageBucket: 'culturelocal-b8f51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGblmJ-Yf0CxnJyW3bU_QXYhdzDDkuYp0',
    appId: '1:122927839963:ios:f537dc1ed25a38b2e1aafe',
    messagingSenderId: '122927839963',
    projectId: 'culturelocal-b8f51',
    storageBucket: 'culturelocal-b8f51.firebasestorage.app',
    iosClientId: '122927839963-migsabk9qegj0db7tpskb6og6mrp77bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.culturelocal',
  );
}
